version: '3.9'
services:
  discovery:
    build:
      context: ./ # Caminho correto do Eureka
      dockerfile: Dockerfile
    container_name: discovery
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - sgu-networks

networks:
  sgu-networks:
    external: true
